/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/correlation-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Admin_GetCorrelationSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["Admin_UpdateCorrelationSettings"];
        trace?: never;
    };
    "/api/v1/admin/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicit, audited data deletion outside the normal retention path. */
        post: operations["Admin_Purge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Admin_GetTenantSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Retention and redaction changes are audited with before and after values. */
        patch: operations["Admin_UpdateTenantSettings"];
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Admin_ListUsers"];
        put?: never;
        post: operations["Admin_CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["Admin_DeleteUser"];
        options?: never;
        head?: never;
        patch: operations["Admin_UpdateUser"];
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Alerts_ListAlertRules"];
        put?: never;
        /** @description The condition is validated and dry-run against recent data before it is stored. */
        post: operations["Alerts_CreateAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Disables the rule. Its alerts are kept: an alert whose rule has vanished cannot
         *      be explained afterwards.
         */
        delete: operations["Alerts_DeleteAlertRule"];
        options?: never;
        head?: never;
        patch: operations["Alerts_UpdateAlertRule"];
        trace?: never;
    };
    "/api/v1/alert-rules/{ruleId}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Measures a condition over recent data WITHOUT firing anything, so an author can
         *      see what their threshold would have caught before committing to it.
         */
        post: operations["Alerts_PreviewAlertRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Alerts_ListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Alerts_GetAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Alerts_AcknowledgeAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alertId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Alerts_ResolveAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only. There is deliberately no operation that writes, edits, or deletes an
         *      audit entry.
         */
        get: operations["Admin_ListAuditEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Step 1: verify the password. Returns an MFA challenge, never an access token. */
        post: operations["Auth_Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_Logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_Me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Step 2: verify the TOTP code and issue the token pair. */
        post: operations["Auth_VerifyMFA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Exchange a refresh token for a new pair. The presented refresh token is revoked. */
        post: operations["Auth_Refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Correlation_ListCorrelatedRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlated/{correlationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Correlation_GetCorrelatedRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/disagreements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboards_GetDisagreements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/feed-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboards_GetFeedHealthPanel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboards_GetOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboards_GetRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Dashboards_GetSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The raw vendor payload alongside the normalized view, so an analyst can always
         *      check what the platform did to a record (FR-005).
         */
        get: operations["Search_GetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Feeds_ListFeeds"];
        put?: never;
        /** @description The credential is accepted here, stored in the secret manager, and never echoed. */
        post: operations["Feeds_CreateFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Feeds_GetFeed"];
        put?: never;
        post?: never;
        /** @description Soft-disables the feed. Ingested data is never removed by this operation. */
        delete: operations["Feeds_DeleteFeed"];
        options?: never;
        head?: never;
        patch: operations["Feeds_UpdateFeed"];
        trace?: never;
    };
    "/api/v1/feeds/{feedId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Feeds_GetFeedHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feedId}/rejected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dead-lettered events, so a rejected delivery is visible rather than silent. */
        get: operations["Feeds_ListRejectedEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feedId}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Feeds_TestFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/correlated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Search_SearchCorrelated"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Search_SearchEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Streamed and row-capped. Audited with the actor, the query, and the row count,
         *      because an export removes data from the platform's control (FR-026).
         */
        post: operations["Search_ExportSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcknowledgeAlertRequest: {
            alertId?: string;
            note?: string;
        };
        Alert: {
            alertId?: string;
            ruleId?: string;
            ruleName?: string;
            /** Format: date-time */
            firedAt?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_LOW" | "SEVERITY_MEDIUM" | "SEVERITY_HIGH" | "SEVERITY_CRITICAL";
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "ALERT_STATE_UNSPECIFIED" | "ALERT_STATE_NEW" | "ALERT_STATE_ACKNOWLEDGED" | "ALERT_STATE_RESOLVED";
            groupValues?: {
                [key: string]: string;
            };
            /** Format: double */
            observedValue?: number;
            /** Format: double */
            threshold?: number;
            /**
             * @description Links to the correlated records that caused the alert, so an operator opens the
             *      evidence rather than reconstructing the query behind a number (SC-006).
             */
            evidenceCorrelationIds?: string[];
            acknowledgedBy?: string;
            /** Format: date-time */
            acknowledgedAt?: string;
            resolvedBy?: string;
            /** Format: date-time */
            resolvedAt?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            notifyStatus?: "NOTIFY_STATUS_UNSPECIFIED" | "NOTIFY_STATUS_PENDING" | "NOTIFY_STATUS_DELIVERED" | "NOTIFY_STATUS_FAILED";
            /** Format: uint32 */
            notifyAttempts?: number;
            /**
             * @description The last delivery error, shown in the console so a failure is visible where the
             *      alert is rather than only in a log an analyst cannot read.
             */
            notifyLastError?: string;
        };
        AlertRule: {
            ruleId?: string;
            name?: string;
            enabled?: boolean;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_LOW" | "SEVERITY_MEDIUM" | "SEVERITY_HIGH" | "SEVERITY_CRITICAL";
            condition?: components["schemas"]["RuleCondition"];
            webhookUrl?: string;
            /** @description True when a signing secret is configured. The secret itself is NEVER returned. */
            webhookSigningConfigured?: boolean;
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuditEntry: {
            entryId?: string;
            /** Format: date-time */
            occurredAt?: string;
            actorEmail?: string;
            sourceIp?: string;
            action?: string;
            targetType?: string;
            targetId?: string;
            beforeValue?: string;
            afterValue?: string;
            result?: string;
            detail?: string;
            /**
             * @description The hash chain. Exposed so a reader can verify the LINKAGE themselves rather than
             *      take the platform's word for it — an audit trail whose integrity can only be
             *      confirmed by the system that wrote it is not evidence.
             *
             *      Checking these proves no entry was removed from the middle of a range: a deletion
             *      breaks the chain where it happened. It does NOT prove the whole range was not
             *      rewritten from the start; that needs the server-held anchor.
             */
            entryHash?: string;
            previousHash?: string;
        };
        /** @description ClientInfo describes the requesting client as normalized across vendors. */
        ClientInfo: {
            ip?: string;
            /**
             * @description True when the address looks like NAT, a proxy chain, or a carrier range. This
             *      downgrades join confidence rather than silently weakening the match.
             */
            ipShared?: boolean;
            /** Format: uint32 */
            asn?: number;
            country?: string;
            userAgent?: string;
        };
        /** @description CorrelatedFilters add the join-level facets to the event filters. */
        CorrelatedFilters: {
            clientIp?: string;
            requestHost?: string;
            requestPath?: string;
            country?: string;
            /** Format: uint32 */
            asn?: number;
            /**
             * Format: uint32
             * @description Above 1 restricts the result to genuine cross-vendor joins.
             */
            minVendorCount?: number;
            onlyDisagreements?: boolean;
            /**
             * Format: enum
             * @enum {string}
             */
            disagreementKind?: "DISAGREEMENT_KIND_UNSPECIFIED" | "DISAGREEMENT_KIND_NONE" | "DISAGREEMENT_KIND_ALLOW_VS_BLOCK" | "DISAGREEMENT_KIND_ALLOW_VS_CHALLENGE" | "DISAGREEMENT_KIND_SCORE_CONFLICT";
            /**
             * Format: enum
             * @enum {string}
             */
            confidence?: "CONFIDENCE_UNSPECIFIED" | "CONFIDENCE_HIGH" | "CONFIDENCE_MEDIUM" | "CONFIDENCE_LOW";
            /**
             * Format: enum
             * @enum {string}
             */
            combinedOutcome?: "VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN";
        };
        /** @description CorrelatedRequest is one request as every vendor that saw it reported it. */
        CorrelatedRequest: {
            correlationId?: string;
            /** Format: date-time */
            windowStart?: string;
            /** Format: date-time */
            firstEventTime?: string;
            /** Format: date-time */
            lastEventTime?: string;
            client?: components["schemas"]["ClientInfo"];
            request?: components["schemas"]["RequestInfo"];
            /**
             * @description One entry per contributing vendor, so a disagreement can be read directly off
             *      the record rather than inferred from a flattened summary.
             */
            vendorVerdicts?: components["schemas"]["VendorVerdict"][];
            /**
             * Format: uint32
             * @description 1 is normal, not an error: plenty of hostnames sit behind a single vendor (FR-016).
             */
            vendorCount?: number;
            /** @description Ids of the contributing events, for drilling through to the raw payloads (FR-024). */
            eventIds?: string[];
            /**
             * Format: enum
             * @description The most restrictive verdict any vendor reached.
             * @enum {string}
             */
            combinedOutcome?: "VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN";
            hasDisagreement?: boolean;
            /**
             * Format: enum
             * @enum {string}
             */
            disagreementKind?: "DISAGREEMENT_KIND_UNSPECIFIED" | "DISAGREEMENT_KIND_NONE" | "DISAGREEMENT_KIND_ALLOW_VS_BLOCK" | "DISAGREEMENT_KIND_ALLOW_VS_CHALLENGE" | "DISAGREEMENT_KIND_SCORE_CONFLICT";
            joinSignals?: ("JOIN_SIGNAL_UNSPECIFIED" | "JOIN_SIGNAL_VENDOR_REQUEST_ID" | "JOIN_SIGNAL_IP_HOST_PATH_METHOD" | "JOIN_SIGNAL_TIME_WINDOW")[];
            /**
             * Format: uint32
             * @description 1 = exact shared request id, 2 = heuristic match.
             */
            joinTier?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            confidence?: "CONFIDENCE_UNSPECIFIED" | "CONFIDENCE_HIGH" | "CONFIDENCE_MEDIUM" | "CONFIDENCE_LOW";
            /**
             * Format: uint32
             * @description Above 1, several events competed for the join and the chosen one may be wrong.
             */
            candidateCount?: number;
            /**
             * @description Increments each time a late arrival amends the record. The correlation_id never
             *      changes, so a bookmarked record stays findable.
             */
            version?: string;
            amended?: boolean;
        };
        CorrelationSettings: {
            /**
             * Format: uint32
             * @description How far apart two events may be and still describe the same request.
             */
            correlationWindowMs?: number;
            /**
             * Format: uint32
             * @description How late an event may arrive and still amend an existing correlated record.
             */
            latenessBoundMs?: number;
            /** @description Ranked join signals, most trusted first. */
            signalRanking?: ("JOIN_SIGNAL_UNSPECIFIED" | "JOIN_SIGNAL_VENDOR_REQUEST_ID" | "JOIN_SIGNAL_IP_HOST_PATH_METHOD" | "JOIN_SIGNAL_TIME_WINDOW")[];
        };
        CreateAlertRuleRequest: {
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_LOW" | "SEVERITY_MEDIUM" | "SEVERITY_HIGH" | "SEVERITY_CRITICAL";
            condition?: components["schemas"]["RuleCondition"];
            webhookUrl?: string;
            /** @description Accepted here, stored in the secret manager, and never echoed back. */
            webhookSecret?: string;
            enabled?: boolean;
        };
        CreateFeedRequest: {
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            deliveryMode?: "DELIVERY_MODE_UNSPECIFIED" | "DELIVERY_MODE_PUSH" | "DELIVERY_MODE_PULL";
            /** @description Write-only. Supplied once, stored in the secret manager, never read back. */
            credential?: string;
            /** @description Optional HMAC key for vendors that sign their deliveries. */
            signingSecret?: string;
            pullConfig?: string;
            /** Format: uint32 */
            quotaEventsPerSec?: number;
            quotaBytesPerDay?: string;
        };
        CreateUserRequest: {
            email?: string;
            password?: string;
            role?: string;
        };
        DeleteAlertRuleResponse: {
            disabled?: boolean;
        };
        DeleteFeedResponse: Record<string, never>;
        DeleteUserResponse: Record<string, never>;
        DisagreementPoint: {
            /** Format: date-time */
            bucket?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "DISAGREEMENT_KIND_UNSPECIFIED" | "DISAGREEMENT_KIND_NONE" | "DISAGREEMENT_KIND_ALLOW_VS_BLOCK" | "DISAGREEMENT_KIND_ALLOW_VS_CHALLENGE" | "DISAGREEMENT_KIND_SCORE_CONFLICT";
            records?: string;
            /**
             * @description Every correlated request in the bucket. Carried alongside the numerator so a rate
             *      can be computed from one row rather than by dividing figures fetched separately,
             *      which is how two panels on one screen end up disagreeing.
             */
            total?: string;
        };
        DisagreementsPanel: {
            points?: components["schemas"]["DisagreementPoint"][];
            totalRecords?: string;
            totalDisagreements?: string;
        };
        /** @description EventDetail is one event with everything the platform holds about it. */
        EventDetail: {
            summary?: components["schemas"]["EventSummary"];
            /**
             * @description The vendor payload exactly as received, written before any parsing was attempted
             *      so a parse failure can never cost the original (FR-005).
             */
            rawPayload?: string;
            rawContentType?: string;
            /**
             * @description Vendor-native fields with no common-model home (FR-012).
             *
             *      Reconstructed from raw_payload on read rather than stored: it is a parsed view of
             *      those same bytes, and keeping both cost 12.79 GiB to say twice what the payload
             *      already said once. The tenant's redaction policy is re-applied when it is rebuilt,
             *      so a masked field is masked here exactly as it was when stored.
             */
            rawExtra?: {
                [key: string]: string;
            };
            /** @description Set when this event was correlated with others, for drill-through. */
            correlationId?: string;
            /**
             * @description Vendor fields the adapter did not recognise, for the event being inspected.
             *      Reconstructed alongside raw_extra from the same parse.
             */
            unknownFields?: string[];
        };
        /**
         * @description EventFilters are the cross-vendor filters an analyst can apply.
         *
         *      Every field here is optional and every one is validated against an allowlist before
         *      it reaches SQL. Unset fields are omitted from the query rather than matched against
         *      an empty string, so a blank filter widens nothing.
         */
        EventFilters: {
            clientIp?: string;
            requestHost?: string;
            requestPath?: string;
            vendor?: ("VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME")[];
            verdict?: ("VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN")[];
            ruleId?: string;
            /** Format: float */
            minScore?: number;
            /** Format: float */
            maxScore?: number;
            country?: string;
            /** Format: uint32 */
            asn?: number;
            userAgent?: string;
            /**
             * @description Free-text match across the request path and user agent, backed by the token bloom
             *      indexes. Not a general full-text search: a substring scan over every column could
             *      not meet the latency budget and would quietly become the slowest query in the app.
             */
            q?: string;
            vendorRequestId?: string;
            requestMethod?: string;
            /** Format: uint32 */
            httpStatus?: number;
        };
        /**
         * @description EventSummary is one search hit.
         *
         *      Deliberately narrower than the detail view: the raw vendor payload is excluded, so a
         *      thousand-row page stays kilobytes rather than tens of megabytes. GetEvent fetches
         *      the payload for the one row an analyst opens.
         */
        EventSummary: {
            eventId?: string;
            /** Format: date-time */
            eventTime?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            feedId?: string;
            vendorRequestId?: string;
            client?: components["schemas"]["ClientInfo"];
            request?: components["schemas"]["RequestInfo"];
            /**
             * Format: enum
             * @enum {string}
             */
            verdict?: "VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN";
            verdictReason?: string;
            ruleId?: string;
            ruleIds?: string[];
            /** Format: float */
            score?: number;
            scoreKind?: string;
        };
        ExportSearchRequest: {
            timeRange?: components["schemas"]["TimeRange"];
            filters?: components["schemas"]["EventFilters"];
            /**
             * Format: enum
             * @enum {string}
             */
            format?: "EXPORT_FORMAT_UNSPECIFIED" | "EXPORT_FORMAT_NDJSON" | "EXPORT_FORMAT_CSV";
            /**
             * Format: uint32
             * @description Capped server-side regardless of what is requested.
             */
            maxRows?: number;
        };
        ExportSearchResponse: {
            /**
             * Format: bytes
             * @description The export content, streamed to the caller.
             */
            content?: string;
            contentType?: string;
            filename?: string;
            /**
             * @description Signed, matching PageResponse.total: row counts are one concept and should not
             *      change type depending on which message carries them.
             */
            rowCount?: string;
            /**
             * @description True when the export stopped at the row cap, so the caller knows the file is a
             *      prefix of the result rather than all of it.
             */
            truncated?: boolean;
        };
        Feed: {
            feedId?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            deliveryMode?: "DELIVERY_MODE_UNSPECIFIED" | "DELIVERY_MODE_PUSH" | "DELIVERY_MODE_PULL";
            enabled?: boolean;
            /** @description True when a credential is configured. The credential itself is NEVER returned. */
            credentialConfigured?: boolean;
            signingConfigured?: boolean;
            pullConfig?: string;
            /** Format: uint32 */
            quotaEventsPerSec?: number;
            quotaBytesPerDay?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @description Populated on list and get so the console can show status without a second call. */
            health?: components["schemas"]["FeedHealth"];
        };
        /**
         * @description FeedHealth answers "is this feed working" (FR-008).
         *
         *      Silence detection lives here because a feed that stopped sending looks exactly like
         *      clean traffic on a dashboard. `silent` is what distinguishes them.
         */
        FeedHealth: {
            feedId?: string;
            /** Format: date-time */
            lastEventAt?: string;
            /** @description True when nothing has arrived for longer than the expected interval. */
            silent?: boolean;
            /** Format: double */
            eventsPerSec?: number;
            eventsReceived1h?: string;
            eventsRejected1h?: string;
            duplicatesSuppressed1h?: string;
            bytesReceived1h?: string;
            /** Format: uint32 */
            maxIngestLagMs?: number;
            credentialValid?: boolean;
            /** @description Set when unrecognized vendor fields crossed the drift threshold (FR-012). */
            schemaDriftWarning?: boolean;
            driftFields?: string[];
        };
        FeedHealthPanel: {
            feeds?: components["schemas"]["FeedHealth"][];
        };
        /**
         * @description IngestFilterRule excludes matching events from ingestion entirely.
         *
         *      A matched event is stored NOWHERE — no raw payload, no normalized row, no rejection —
         *      so the only trace it leaves is the filtered counter on feed health. That is why the
         *      vocabulary is closed and literal rather than a regular expression: a rule an operator
         *      can misread is a rule that silently deletes the traffic they needed, and unlike every
         *      other loss in this system there is no copy to recover from.
         */
        IngestFilterRule: {
            /** @description One of: request_host, request_path. */
            field?: string;
            /**
             * @description One of: equals, suffix, prefix, contains. Matching ignores case, because hostnames
             *      are case-insensitive and extensions arrive in both cases from real traffic.
             */
            op?: string;
            /** @description Any value matching drops the event, as does any rule — the whole set is an OR. */
            values?: string[];
        };
        ListAlertRulesResponse: {
            rules?: components["schemas"]["AlertRule"][];
        };
        ListAlertsResponse: {
            alerts?: components["schemas"]["Alert"][];
            page?: components["schemas"]["PageResponse"];
        };
        ListAuditEntriesResponse: {
            entries?: components["schemas"]["AuditEntry"][];
            page?: components["schemas"]["PageResponse"];
            /**
             * @description False when the hash chain over the returned range does not verify, meaning an
             *      entry was altered or removed.
             */
            chainIntact?: boolean;
        };
        ListCorrelatedRequestsResponse: {
            requests?: components["schemas"]["CorrelatedRequest"][];
            page?: components["schemas"]["PageResponse"];
        };
        ListFeedsResponse: {
            feeds?: components["schemas"]["Feed"][];
        };
        ListRejectedEventsResponse: {
            events?: components["schemas"]["RejectedEvent"][];
            page?: components["schemas"]["PageResponse"];
        };
        ListUsersResponse: {
            users?: components["schemas"]["UserProfile"][];
            page?: components["schemas"]["PageResponse"];
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        LoginResponse: {
            /** @description Short-lived token proving the password step succeeded. Grants nothing else. */
            mfaChallengeToken?: string;
            /** @description True on first login, when the client must render the enrolment QR code. */
            mfaEnrolmentRequired?: boolean;
            /** @description Populated only during enrolment, and never again afterwards. */
            mfaProvisioningUri?: string;
        };
        LogoutRequest: {
            refreshToken?: string;
        };
        LogoutResponse: Record<string, never>;
        MeResponse: {
            user?: components["schemas"]["UserProfile"];
        };
        OverviewPanel: {
            volume?: components["schemas"]["VolumePoint"][];
            verdicts?: components["schemas"]["VerdictPoint"][];
            /**
             * @description Totals for the whole range, so a headline figure does not require the client to
             *      re-sum the series and risk disagreeing with it.
             */
            totalEvents?: string;
            totalBlocked?: string;
            totalChallenged?: string;
        };
        /**
         * @description PageRequest carries cursor-based paging. Offsets are never used — they skip and
         *      repeat rows when data arrives mid-pagination, which this system does constantly.
         */
        PageRequest: {
            /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
            cursor?: string;
            /**
             * Format: int32
             * @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested.
             */
            limit?: number;
        };
        PageResponse: {
            /** @description Empty when there are no further pages. */
            nextCursor?: string;
            /**
             * @description Approximate match count. Exact counts over hundreds of millions of rows cannot
             *      meet the latency budget, so the API states when a count is an estimate rather
             *      than implying precision it does not have.
             */
            total?: string;
            totalIsEstimate?: boolean;
        };
        PreviewAlertRuleRequest: {
            /** @description Empty when previewing an unsaved rule. */
            ruleId?: string;
            /**
             * @description The condition to measure. Required, so an author can preview an edit before
             *      saving it rather than only after.
             */
            condition?: components["schemas"]["RuleCondition"];
            /** @description How far back to measure. Defaults to the condition's own window. */
            timeRange?: components["schemas"]["TimeRange"];
        };
        PreviewAlertRuleResponse: {
            groups?: components["schemas"]["PreviewGroup"][];
            /** Format: uint32 */
            wouldFireCount?: number;
        };
        /** @description PreviewGroup is one group's measurement in a dry run. */
        PreviewGroup: {
            groupValues?: {
                [key: string]: string;
            };
            /** Format: double */
            observedValue?: number;
            /** Format: double */
            total?: number;
            /**
             * @description Whether this group WOULD have fired. Groups that would not fire are returned too:
             *      an author tuning a threshold needs to see the values it did not trip on.
             */
            wouldFire?: boolean;
            evidenceCorrelationIds?: string[];
        };
        PurgeRequest: {
            range?: components["schemas"]["TimeRange"];
            /**
             * @description Must equal the tenant name. A destructive operation should not be reachable by
             *      an accidental click.
             */
            confirmation?: string;
            reason?: string;
        };
        PurgeResponse: {
            rowsDeleted?: string;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        RejectedEvent: {
            /** Format: date-time */
            rejectedAt?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            reasonCode?: string;
            reasonDetail?: string;
            /**
             * @description The offending payload, so an operator can see exactly what the vendor sent.
             *      Rendered as inert text by the console.
             */
            payload?: string;
            batchId?: string;
        };
        /** @description RequestInfo describes the HTTP request as normalized across vendors. */
        RequestInfo: {
            host?: string;
            path?: string;
            query?: string;
            method?: string;
            /** Format: uint32 */
            status?: number;
        };
        ResolveAlertRequest: {
            alertId?: string;
            note?: string;
        };
        /**
         * @description RuleCondition is what a rule matches and measures.
         *
         *      A closed structure rather than an expression language: an operator writing a rule
         *      must not be able to author something that scans without bounds or references a
         *      column that does not exist.
         */
        RuleCondition: {
            /**
             * @description Filters narrow which correlated requests the rule considers. Field names are
             *      validated against the same allowlist a search uses.
             */
            filters?: {
                [key: string]: string;
            };
            onlyDisagreements?: boolean;
            /** Format: uint32 */
            minVendorCount?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            aggregate?: "RULE_AGGREGATE_UNSPECIFIED" | "RULE_AGGREGATE_COUNT" | "RULE_AGGREGATE_RATE" | "RULE_AGGREGATE_DISTINCT_IPS";
            /**
             * Format: enum
             * @enum {string}
             */
            comparator?: "RULE_COMPARATOR_UNSPECIFIED" | "RULE_COMPARATOR_GT" | "RULE_COMPARATOR_GTE" | "RULE_COMPARATOR_LT" | "RULE_COMPARATOR_LTE";
            /** Format: double */
            threshold?: number;
            /** Format: uint32 */
            windowSeconds?: number;
            /** @description Each group is a separate alert and a separate cooldown, so this is capped. */
            groupBy?: string[];
            /**
             * Format: uint32
             * @description Must be at least as long as the window, or one sustained condition produces a
             *      stream of duplicate alerts.
             */
            cooldownSeconds?: number;
        };
        RuleCount: {
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            ruleId?: string;
            events?: string;
        };
        RulesPanel: {
            rules?: components["schemas"]["RuleCount"][];
        };
        SearchCorrelatedRequest: {
            timeRange?: components["schemas"]["TimeRange"];
            filters?: components["schemas"]["CorrelatedFilters"];
            page?: components["schemas"]["PageRequest"];
        };
        SearchCorrelatedResponse: {
            items?: components["schemas"]["CorrelatedRequest"][];
            page?: components["schemas"]["PageResponse"];
        };
        SearchEventsRequest: {
            /** @description Required. An unbounded scan is rejected, not queued. */
            timeRange?: components["schemas"]["TimeRange"];
            filters?: components["schemas"]["EventFilters"];
            page?: components["schemas"]["PageRequest"];
        };
        SearchEventsResponse: {
            items?: components["schemas"]["EventSummary"][];
            /**
             * @description Carries next_cursor, total, and total_is_estimate. Those live on PageResponse
             *      rather than being repeated here: two places stating the same count is two places
             *      to keep in step, and they will not stay in step.
             */
            page?: components["schemas"]["PageResponse"];
        };
        SourceCount: {
            clientIp?: string;
            country?: string;
            /** Format: uint32 */
            asn?: number;
            events?: string;
            /**
             * @description A subset of events, never a separate tally: a source showing more blocks than
             *      requests is nonsense an analyst cannot act on.
             */
            blocked?: string;
        };
        SourcesPanel: {
            sources?: components["schemas"]["SourceCount"][];
        };
        TenantSettings: {
            tenantId?: string;
            name?: string;
            status?: string;
            /** Format: uint32 */
            rawRetentionDays?: number;
            /** Format: uint32 */
            correlatedRetentionDays?: number;
            /** Format: uint32 */
            alertRetentionDays?: number;
            /** @description Fields masked at ingest, so they are never stored in readable form. */
            redactedFields?: string[];
            /** Format: float */
            scoreConflictThreshold?: number;
            /** @description Events matching any of these are never ingested at all. */
            ingestFilters?: components["schemas"]["IngestFilterRule"][];
        };
        TestFeedRequest: {
            feedId?: string;
        };
        TestFeedResponse: {
            reachable?: boolean;
            credentialValid?: boolean;
            /** @description Human-readable outcome. Never contains the credential or an internal address. */
            detail?: string;
        };
        /**
         * @description TimeRange bounds a query. Both ends are REQUIRED on every event-data read:
         *      unbounded scans are rejected, not queued (Constitution Principle V).
         */
        TimeRange: {
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: date-time */
            expiresAt?: string;
            user?: components["schemas"]["UserProfile"];
        };
        UpdateAlertRuleRequest: {
            ruleId?: string;
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_LOW" | "SEVERITY_MEDIUM" | "SEVERITY_HIGH" | "SEVERITY_CRITICAL";
            condition?: components["schemas"]["RuleCondition"];
            webhookUrl?: string;
            webhookSecret?: string;
            enabled?: boolean;
        };
        UpdateCorrelationSettingsRequest: {
            /** Format: uint32 */
            correlationWindowMs?: number;
            /** Format: uint32 */
            latenessBoundMs?: number;
            signalRanking?: ("JOIN_SIGNAL_UNSPECIFIED" | "JOIN_SIGNAL_VENDOR_REQUEST_ID" | "JOIN_SIGNAL_IP_HOST_PATH_METHOD" | "JOIN_SIGNAL_TIME_WINDOW")[];
        };
        UpdateFeedRequest: {
            feedId?: string;
            name?: string;
            enabled?: boolean;
            /** @description Rotates the credential. Omitted leaves the existing one in place. */
            credential?: string;
            signingSecret?: string;
            pullConfig?: string;
            /** Format: uint32 */
            quotaEventsPerSec?: number;
            quotaBytesPerDay?: string;
        };
        UpdateTenantSettingsRequest: {
            /** Format: uint32 */
            rawRetentionDays?: number;
            /** Format: uint32 */
            correlatedRetentionDays?: number;
            /** Format: uint32 */
            alertRetentionDays?: number;
            redactedFields?: string[];
            /** Format: float */
            scoreConflictThreshold?: number;
            /**
             * @description Replaces the whole rule set rather than merging: a partial update has no obvious
             *      meaning for a list, and "remove this one rule" must not require knowing which
             *      position it occupies.
             */
            ingestFilters?: components["schemas"]["IngestFilterRule"][];
        };
        UpdateUserRequest: {
            userId?: string;
            role?: string;
            status?: string;
            /** @description Setting this resets MFA enrolment, forcing re-enrolment on next login. */
            resetMfa?: boolean;
        };
        UserProfile: {
            userId?: string;
            email?: string;
            /** @description admin | analyst | auditor | ingest_only */
            role?: string;
            tenantId?: string;
            tenantName?: string;
            mfaEnabled?: boolean;
            /** Format: date-time */
            lastLoginAt?: string;
        };
        /** @description VendorVerdict is one vendor's contribution to a correlated request. */
        VendorVerdict: {
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            /**
             * Format: enum
             * @enum {string}
             */
            verdict?: "VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN";
            verdictReason?: string;
            ruleId?: string;
            ruleIds?: string[];
            /**
             * Format: float
             * @description Absent when the vendor does not score requests.
             */
            score?: number;
            scoreKind?: string;
            eventId?: string;
            /** Format: date-time */
            eventTime?: string;
        };
        /** @description VerdictPoint is one vendor's verdict count in one bucket. */
        VerdictPoint: {
            /** Format: date-time */
            bucket?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            /**
             * Format: enum
             * @enum {string}
             */
            verdict?: "VERDICT_UNSPECIFIED" | "VERDICT_ALLOWED" | "VERDICT_BLOCKED" | "VERDICT_CHALLENGED" | "VERDICT_RATE_LIMITED" | "VERDICT_MONITORED" | "VERDICT_UNKNOWN";
            events?: string;
        };
        VerifyMFARequest: {
            mfaChallengeToken?: string;
            code?: string;
        };
        /** @description VolumePoint is one vendor's traffic in one bucket. */
        VolumePoint: {
            /** Format: date-time */
            bucket?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            vendor?: "VENDOR_UNSPECIFIED" | "VENDOR_CLOUDFLARE" | "VENDOR_F5" | "VENDOR_DATADOME";
            events?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Admin_GetCorrelationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationSettings"];
                };
            };
        };
    };
    Admin_UpdateCorrelationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCorrelationSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationSettings"];
                };
            };
        };
    };
    Admin_Purge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurgeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResponse"];
                };
            };
        };
    };
    Admin_GetTenantSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettings"];
                };
            };
        };
    };
    Admin_UpdateTenantSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantSettingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettings"];
                };
            };
        };
    };
    Admin_ListUsers: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
                "page.cursor"?: string;
                /** @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested. */
                "page.limit"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
        };
    };
    Admin_CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    Admin_DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteUserResponse"];
                };
            };
        };
    };
    Admin_UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    Alerts_ListAlertRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertRulesResponse"];
                };
            };
        };
    };
    Alerts_CreateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    Alerts_DeleteAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAlertRuleResponse"];
                };
            };
        };
    };
    Alerts_UpdateAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
        };
    };
    Alerts_PreviewAlertRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Empty when previewing an unsaved rule. */
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewAlertRuleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewAlertRuleResponse"];
                };
            };
        };
    };
    Alerts_ListAlerts: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                state?: "ALERT_STATE_UNSPECIFIED" | "ALERT_STATE_NEW" | "ALERT_STATE_ACKNOWLEDGED" | "ALERT_STATE_RESOLVED";
                severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_LOW" | "SEVERITY_MEDIUM" | "SEVERITY_HIGH" | "SEVERITY_CRITICAL";
                ruleId?: string;
                /**
                 * @description Filters to alerts whose notification failed, which is the operator's other entry
                 *      point: "what did we fail to send".
                 */
                notifyStatus?: "NOTIFY_STATUS_UNSPECIFIED" | "NOTIFY_STATUS_PENDING" | "NOTIFY_STATUS_DELIVERED" | "NOTIFY_STATUS_FAILED";
                /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
                "page.cursor"?: string;
                /** @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested. */
                "page.limit"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertsResponse"];
                };
            };
        };
    };
    Alerts_GetAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    Alerts_AcknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgeAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    Alerts_ResolveAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    Admin_ListAuditEntries: {
        parameters: {
            query?: {
                "range.from"?: string;
                "range.to"?: string;
                /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
                "page.cursor"?: string;
                /** @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested. */
                "page.limit"?: number;
                action?: string;
                actorEmail?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAuditEntriesResponse"];
                };
            };
        };
    };
    Auth_Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    Auth_Logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    Auth_Me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    Auth_VerifyMFA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyMFARequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    Auth_Refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    Correlation_ListCorrelatedRequests: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                /** @description Optional filter; unspecified returns every confidence level. */
                confidence?: "CONFIDENCE_UNSPECIFIED" | "CONFIDENCE_HIGH" | "CONFIDENCE_MEDIUM" | "CONFIDENCE_LOW";
                /** @description Restricts the result to records where vendors reached conflicting verdicts. */
                onlyDisagreements?: boolean;
                /** @description Restricts the result to genuine cross-vendor joins when set above 1. */
                minVendorCount?: number;
                /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
                "page.cursor"?: string;
                /** @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested. */
                "page.limit"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCorrelatedRequestsResponse"];
                };
            };
        };
    };
    Correlation_GetCorrelatedRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                correlationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelatedRequest"];
                };
            };
        };
    };
    Dashboards_GetDisagreements: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                interval?: "BUCKET_INTERVAL_UNSPECIFIED" | "BUCKET_INTERVAL_5M" | "BUCKET_INTERVAL_1H" | "BUCKET_INTERVAL_1D";
                /** @description Caps the rows a top-N panel returns. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisagreementsPanel"];
                };
            };
        };
    };
    Dashboards_GetFeedHealthPanel: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                interval?: "BUCKET_INTERVAL_UNSPECIFIED" | "BUCKET_INTERVAL_5M" | "BUCKET_INTERVAL_1H" | "BUCKET_INTERVAL_1D";
                /** @description Caps the rows a top-N panel returns. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealthPanel"];
                };
            };
        };
    };
    Dashboards_GetOverview: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                interval?: "BUCKET_INTERVAL_UNSPECIFIED" | "BUCKET_INTERVAL_5M" | "BUCKET_INTERVAL_1H" | "BUCKET_INTERVAL_1D";
                /** @description Caps the rows a top-N panel returns. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewPanel"];
                };
            };
        };
    };
    Dashboards_GetRules: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                interval?: "BUCKET_INTERVAL_UNSPECIFIED" | "BUCKET_INTERVAL_5M" | "BUCKET_INTERVAL_1H" | "BUCKET_INTERVAL_1D";
                /** @description Caps the rows a top-N panel returns. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesPanel"];
                };
            };
        };
    };
    Dashboards_GetSources: {
        parameters: {
            query?: {
                "timeRange.from"?: string;
                "timeRange.to"?: string;
                interval?: "BUCKET_INTERVAL_UNSPECIFIED" | "BUCKET_INTERVAL_5M" | "BUCKET_INTERVAL_1H" | "BUCKET_INTERVAL_1D";
                /** @description Caps the rows a top-N panel returns. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesPanel"];
                };
            };
        };
    };
    Search_GetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    Feeds_ListFeeds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFeedsResponse"];
                };
            };
        };
    };
    Feeds_CreateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
        };
    };
    Feeds_GetFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
        };
    };
    Feeds_DeleteFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteFeedResponse"];
                };
            };
        };
    };
    Feeds_UpdateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
        };
    };
    Feeds_GetFeedHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedHealth"];
                };
            };
        };
    };
    Feeds_ListRejectedEvents: {
        parameters: {
            query?: {
                "range.from"?: string;
                "range.to"?: string;
                reasonCode?: string;
                /** @description Opaque cursor from a previous PageResponse. Empty requests the first page. */
                "page.cursor"?: string;
                /** @description Server caps this at QUERY_MAX_RESULT_ROWS regardless of what is requested. */
                "page.limit"?: number;
            };
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRejectedEventsResponse"];
                };
            };
        };
    };
    Feeds_TestFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestFeedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestFeedResponse"];
                };
            };
        };
    };
    Search_SearchCorrelated: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchCorrelatedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchCorrelatedResponse"];
                };
            };
        };
    };
    Search_SearchEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchEventsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchEventsResponse"];
                };
            };
        };
    };
    Search_ExportSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportSearchRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSearchResponse"];
                };
            };
        };
    };
}
